#!/bin/bash

rootDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

dc=dmd
#dc=$rootDir/util/dmd2/linux/bin64/dmd
#export LIBRARY_PATH=$rootDir/util/dmd2/linux/lib64
#export LD_LIBRARY_PATH=$rootDir/util/dmd2/linux/lib64
defaultlib="libphobos2.so" # libphobos2-ldc

#params for debug
defBuildParams="-debug -g" # -debug=data -debug=tick
defLinkParams="-g"

#params for release
#defBuildParams="-release"
#defLinkParams=""

if [ $1 ]; then buildType=$1; else buildType=debug; fi
buildParams=${@:2}

# prepare build
rm -fr $rootDir/bin $rootDir/tst $rootDir/ifc $rootDir/lib $rootDir/ext
mkdir -p $rootDir/bin
mkdir -p $rootDir/tst
mkdir -p $rootDir/ifc
mkdir -p $rootDir/lib
mkdir -p $rootDir/ext

export LIBRARY_PATH=$rootDir/lib:$rootDir/ext:LIBRARY_PATH
export LD_LIBRARY_PATH=$rootDir/lib:$rootDir/ext:LD_LIBRARY_PATH

function buildNanoMsg {
    cd $rootDir/src/lib/nanomsg-wrapper/source &&
    mkdir -p build &&

    echo "BUILDING lib/libnanomsg-wrapper.so ..." &&
    $dc -Hd=$rootDir/ifc/nanomsg -c -ofbuild/libnanomsg-wrapper.o $defBuildParams -w -I$rootDir/ifc/ $(find ./ -name "*.d") -fPIC -vcolumns &&

    echo "LINKING lib/libnanomsg-wrapper.so ..." &&
    $dc -of$rootDir/lib/libnanomsg-wrapper.so build/libnanomsg-wrapper.o -L-l:$defaultlib -L-l:libnanomsg.so -shared -defaultlib=$defaultlib $defLinkParams
}

function buildCore {
    cd $rootDir/src/core &&
    mkdir -p build &&

    echo "BUILDING lib/libflow-core..." &&
    $dc -Hd=$rootDir/ifc -op -c -ofbuild/libflow-core.o $defBuildParams -w -I$rootDir/ifc/ $(find ./ -name "*.d") -fPIC -vcolumns &&

    echo "LINKING lib/libflow-core..." &&
    $dc -of$rootDir/lib/libflow-core.so build/libflow-core.o -L-l:$defaultlib -shared -defaultlib=$defaultlib $defLinkParams
}

function testCore {
    cd $rootDir/src/core &&
    mkdir -p build &&

    echo "BUILDING tst/libflow-core-test..." &&
    $dc -c -ofbuild/libflow-core-test.o $defBuildParams -w -I$rootDir/ifc/ $(find ./ -name "*.d") -fPIC -vcolumns -main -unittest &&

    echo "LINKING tst/libflow-core-test..." &&
    $dc -of$rootDir/tst/test-libflow-core build/libflow-core-test.o -unittest -L-l:$defaultlib -defaultlib=$defaultlib $defLinkParams &&

    $rootDir/tst/test-libflow-core
}

function buildExt {
    cd $rootDir/src/ext/$1 &&
    mkdir -p build &&

    echo "BUILDING ext/libflow-$1..." &&
    $dc -Hd=$rootDir/ifc -op -c -ofbuild/libflow-$1.o $defBuildParams -w -I$rootDir/ifc/ $(find ./ -name "*.d") -fPIC -vcolumns &&

    echo "LINKING ext/libflow-$1..." &&
    $dc -of$rootDir/ext/libflow-$1.so build/libflow-$1.o -L-l:$defaultlib -L-l:libflow-core.so ${@:2} -shared -defaultlib=$defaultlib $defLinkParams
}

function testExt {
    cd $rootDir/src/ext/$1 &&
    mkdir -p build &&

    echo "BUILDING tst/test-libflow-$1..." &&
    $dc -c -ofbuild/libflow-$1-test.o $defBuildParams -w -I$rootDir/ifc/ $(find ./ -name "*.d") -fPIC -vcolumns -main -unittest &&

    echo "LINKING tst/test-libflow-$1..." &&
    $dc -of$rootDir/tst/test-libflow-$1 build/libflow-$1-test.o -unittest -L-l:$defaultlib -L-l:libflow-core.so ${@:2} -defaultlib=$defaultlib $defLinkParams &&

    $rootDir/tst/test-libflow-$1
}

function buildBin {
    cd $rootDir/src/bin/$1 &&
    mkdir -p build &&

    echo "BUILDING $1..." &&
    $dc -c -ofbuild/flow-$1.o $defBuildParams -w -I$rootDir/ifc/ $(find ./ -name "*.d") -vcolumns &&

    echo "LINKING $1..." &&
    $dc -of$rootDir/bin/flow-$1 build/flow-$1.o -L-l:$defaultlib -L-l:libflow-core.so ${@:2} -defaultlib=$defaultlib $defLinkParams
}

function testBin {
    cd $rootDir/src/bin/$1 &&
    mkdir -p build &&

    echo "BUILDING $1-test..." &&
    $dc -c -ofbuild/flow-$1-test.o $defBuildParams -w -I$rootDir/ifc/ $(find ./ -name "*.d") -vcolumns -unittest &&

    echo "LINKING $1-test..." &&
    $dc -of$rootDir/tst/test-flow-$1 build/flow-$1-test.o -L-l:$defaultlib -L-l:libflow-core.so ${@:2} -defaultlib=$defaultlib $defLinkParams &&

    $rootDir/tst/test-flow-$1
}

buildNanoMsg &&

buildCore &&
buildExt ipc-nanomsg -L-l:libnanomsg-wrapper.so &&
#buildBin run &&

buildExt complex &&
#buildBin complex-gen -L-l:libflow-complex.so &&

testCore &&
testExt ipc-nanomsg -L-l:libnanomsg-wrapper.so &&
#testBin run &&

testExt complex #&&
#testBin complex-gen -L-l:libflow-complex.so
