#!/bin/bash

rootDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function cleanLib {
    dub remove-local $rootDir/$1
    rm -fr $rootDir/$1/lib
}

function cleanBin {
    rm -fr $rootDir/$1/bin
}

cleanBin hive/experiments/take01
cleanBin causal

cleanLib alien
clearLib alien-ui
cleanLib util
cleanLib util-ui
cleanLib base
