#!/bin/bash

rootDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export LD_LIBRARY_PATH=$rootDir/util/dmd2/linux/lib64:$rootDir/core/lib:$rootDir/run/bin/lib:$LD_LIBRARY_PATH

$rootDir/complex-gen/bin/flow-complex-gen ${@:1}
