#!/bin/bash

compiler=dmd
defBuildParams="--compiler=$compiler"
if [ $1 ]; then buildType=$1; else buildType=debug; fi
buildParams=${@:2}
rootDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function buildLib {
    dub remove-local $rootDir/$1
    cd $rootDir/$1 &&
    dub test --build $buildType $defBuildParams $buildParams &&
    dub add-local ./
}

function buildBin {
    cd $rootDir/$1 &&
    dub build --compiler=ldc --build $buildType $defBuildParams $buildParams
}

$rootDir/clean

buildLib base &&
buildLib data &&
buildLib net &&
buildLib alien &&
buildLib example/base/lib &&

buildBin example/base/simplekicker &&
buildBin example/base/trainingkicker &&
buildBin example/base/typingmonkeys &&
buildBin example/base/madtypingmonkeys &&
buildBin example/net/http &&
buildBin causal #&&
#buildBin hive/experiments/take01
